OugAssistant_WEB/Controllers/web/Planning/PlanningController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OugAssistant_WEB.Models.Planning;
using OugAssistant.Features.Planning.Model;
using System.Diagnostics;
using System.Text.Json;
using OugAssistant_APP.Interfaces.Planning;
using OugAssistant_APP.Sevices.Planning;

namespace OugAssistant_WEB.Controllers.web.Planning;

public class PlanningController : Controller
{
    private readonly ITaskServices _taskServices;
    private readonly IGoalServices _goalServices;
    private readonly ILogger _logger;

    public PlanningController(ITaskServices taskServices, IGoalServices goalServices, ILogger<PlanningController> logger)
    {
        _taskServices = taskServices;
        _goalServices = goalServices;
        _logger = logger;
        _logger.LogDebug(1, "NLog injected into PlanningController");
    }

    public async Task<IActionResult> Index()
    {
        _logger.LogInformation("PlanningController Index");

        PlanningViewModel taskViewModel = new PlanningViewModel();
        
        taskViewModel.TaskList = await _taskServices.GetAllOugTaskAsync();
        taskViewModel.GoalList = await _goalServices.GetAllOugGoalAsync();
        return View(taskViewModel);
    }

    public async Task<IActionResult> TaskList() {
        _logger.LogInformation("PlanningController TaskList");
        PlanningViewModel taskViewModel = new PlanningViewModel();
        taskViewModel.TaskList = await _taskServices.GetAllOugTaskAsync();
        return PartialView("Task/Task", taskViewModel);
    }

    public async Task<IActionResult> GoalList()
    {
        _logger.LogInformation("PlanningController GoalList");
        PlanningViewModel goalViewModel = new PlanningViewModel();
        goalViewModel.GoalList = await _goalServices.GetAllOugGoalAsync();
        return PartialView("Goal/Goal", goalViewModel);
    }
}

OugAssistant_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OugAssistant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OugAssistant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Planning" asp-action="Index">Planning</a>
                        </li>
                    </ul>
                    <button id="changeThemeBtn"> Theme</button>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OugAssistant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>